version: '3.8'

services:
  sadrobot:
    image: maxxtor/sadrobot:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - ./.env

volumes:
  static_value:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/www/sadrobot.app/static/'

  media_value:
